version: '3'

services:
  kibana:
    image: kibana:8.8.1
    ports:
      - "5601:5601"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Talo-talo1
      MYSQL_DATABASE: ghost_database
      MYSQL_USER: ghost
      MYSQL_PASSWORD: Talo-talo1

volumes:
  mysql_data:

